---
name: Lint
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v2
      with:
        version: 0.14.1
    - run: |
        sudo apt-get install -y build-essential libc6-dev
        zig build --summary all -Drelease-build
        zig fmt --check .
